jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      language: node_js
      node_js: '12'
    - os: linux
      dist: focal
      node_js: '12'
      language: node_js
      services:
        - xvfb
    - os: windows
      node_js: '12'
      language: node_js
      env:
        - YARN_GPG=no
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x scripts/add-osx-cert.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./scripts/add-osx-cert.sh;
    fi
  - npm install -g yarn
script:
  - yarn test
